### ISSUE TITLE
为什么明明是UC脚本却要用GM安装？

### ISSUE THREAD

**Issue by FlameRaptor** [ccloli/Search-By-Image#2]
RT

**Comment by ccloli** [comment]
因为这并不是 UC 脚本而是 GM 脚本

**Comment by FlameRaptor** [comment]
但是为什么扩展名是user.js?

**Comment by ccloli** [comment]
user.js 是 GM 脚本（Chrome Tampermonkey 保存的 userjs 曾经似乎是 tamper.js），没记错的话 UC 脚本应该是 uc.js

**Comment by FlameRaptor** [comment]
额……脑子一时进水……请别在意………………
