### ISSUE TITLE
百度失效

### ISSUE THREAD

**Issue by FlameRaptor** [ccloli/Search-By-Image#3]
点击图片，用百度搜索，会弹到百度图片的首页

**Comment by FlameRaptor** [comment]
已自行解决
把百度的URL改为
http://image.baidu.com/n/pc_search?queryImageUrl={%s}&querySign=1158124882%2C2220364592&fm=index&pos=paste
即可
请作者大大更新

**Comment by ccloli** [comment]
了解，稍候跟进修复

**Comment by ccloli** [comment]
已修复，由于在尝试复现 GF 上的 issue 所以推送晚了 orz
