### ISSUE TITLE
部分图片无法单独查看

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [ccloli/Search-By-Image#4]
直接浏览图片地址时，无法打开，比如 https://i.imgur.com/2qirlr4.jpg
而嵌入页面的时候，可以正常浏览 https://imgur.com/2qirlr4

而部分图片却完全正常，比如
https://i.imgur.com/srTfsIw.jpg
https://imgur.com/srTfsIw

火狐 52.5.3 ESR (x86)  & Greasemonkey 3.17

**Comment by ccloli** [comment]
这是 Imgur 的策略，与脚本无关

**Comment by LakeishaKowalczyk** [comment]
但是关闭脚本后就一切正常，而且似乎不只是 imgur 一个网站这样

**Comment by LakeishaKowalczyk** [comment]
@ccloli 
比如这里也是，单独的图片地址无法打开
https://c2.staticflickr.com/8/7173/13590937575_3b59fbcd15_b.jpg
https://www.reddit.com/r/pic/comments/7vjd74/castle_howard_england/

**Comment by ccloli** [comment]
已测试，Imgur 无论是否开启脚本都会跳转到文章页面，这是 Imgur 的自身 follow 策略；Flickr 未遇到跳转的情况，请检查其他脚本与扩展程序或确认是否是网站自身问题。
