### ISSUE TITLE
whatanime.ga has moved to trace.moe

### ISSUE THREAD

**Issue by soruly** [ccloli/Search-By-Image#5]
Hello, I'm (was) the owner of whatanime.ga
A few days ago, the .ga domain was taken down by freenom T_T,
so the site has moved to https://trace.moe
if you are still actively supporting this project, please update the URL, thank you m(_ _;)m

**Comment by ccloli** [comment]
The URL has been updated. Thank you for your notification, and for creating such an awesome tool. ❤️
